---
abstract: 'Perl extension for stripping HTML markup from text.'
author:
  - 'Alex Bowley <kilinrax@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Strip
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.07
