---
name: HTML-Strip
version: 2.12
abstract: 'Perl extension for stripping HTML markup from text.'
author:
  - 'Alex Bowley <kilinrax@cpan.org>'
license:
  - perl_5
release_status: stable
prereqs:
  runtime:
    recommends:
      HTML::Entities: 0
  build:
    requires:
      ExtUtils::MakeMaker: 0
      Test::More: 0
      Test::Exception: 0
      Encode: 0
      FindBin: 0
  configure:
    requires:
      ExtUtils::MakeMaker: 0
provides:
  HTML::Strip:
    file: Strip.pm
no_index:
  directory:
    - t
    - inc
resources:
  repository:
    url: git://github.com/kilinrax/HTML-Strip.git
    web: https://github.com/kilinrax/HTML-Strip
    type: git
dynamic_config: 0
generated_by: 'Alex Bowley'
meta-spec:
  url: https://metacpan.org/dist/CPAN-Meta/view/lib/CPAN/Meta/Spec.pm
  version: 2
